name = "fwhyadmin"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces
[[kv_namespaces]]
binding = "EVENTS_KV"
id = "464d611d5ad8433cab6bcfba64d8424f"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "2038b95e785545af8486bc353c3cbe62"

[[kv_namespaces]]
binding = "GALLERY_KV"
id = "3cd37bd71260436c8ed12078483e9fa4"

[[kv_namespaces]]
binding = "BLOG_KV"
id = "6ee9ab6b71634a4eb3e66de82d8dfcdc"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "d54801ef0fb0443e850ee532ad1384b6"

# Legacy KV namespaces for migration
[[kv_namespaces]]
binding = "EVENTS_FAREWELL"
id = "6a2dc6b81774454dba76199798f057df"

[[kv_namespaces]]
binding = "EVENTS_HOWDY"
id = "ab5328a2ca6e4f10b9a4537039056cfc"

[[kv_namespaces]]
binding = "bl0wkv"
id = "bbac2eeab45b4d65868a1caa86e053bd"

[[kv_namespaces]]
binding = "fff_kv"
id = "d782ad152f414511ad5013ff268bcb99"

# D1 Database bindings for migration
[[d1_databases]]
binding = "bl0wd1"
database_name = "bl0wd1"
database_id = "a66d8e4a-3c67-48c5-af72-0a511022805a"

[[d1_databases]]
binding = "farewell_list"
database_name = "farewell_list" 
database_id = "264bf2fb-8c23-4216-8c47-03ebcfaeed63"

[[d1_databases]]
binding = "howdy_list"
database_name = "howdy_list"
database_id = "d1d9fa02-0258-412a-b5bb-2c503da87f26"

[[d1_databases]]
binding = "fwhygal0r3_db"
database_name = "fwhygal0r3-db"
database_id = "44c9c30a-ef78-492b-865b-6d6fdc2553bf"

# R2 Bucket bindings
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "fyg410r3"

# Additional buckets for migration
[[r2_buckets]]
binding = "LEGACY_BUCKET"
bucket_name = "unified-assets-dev"

# Custom domains
[[routes]]
pattern = "admin.farewellcafe.com/*"
zone_name = "farewellcafe.com"

# Environment variables
[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://farewellcafe.com,https://www.farewellcafe.com,https://dev.farewellcafe.com,https://admin.farewellcafe.com"
ADMIN_API_TOKEN = "prod-admin-token-2025-secure"

# Staging environment variables
[env.staging.vars]
ENVIRONMENT = "staging"
ALLOWED_ORIGINS = "https://staging.farewellcafe.com,https://admin-staging.farewellcafe.com"
